config/routes.rb
Rails.application.routes.draw do
  get 'informations/index'
  devise_for :users


  resources :users, only: [:show] do
    resources :contacts, only: [:new, :create, :edit, :update]
  end
  root to: 'pages#home'

  get '/stop', to: 'pages#stop'
  get '/resources', to: 'pages#resources'
  get '/resources/documents', to: 'documents#index', as: :documents
  get '/resources/contacts', to: 'informations#index', as: :informations
  get '/resources/documents/:id', to: 'documents#show', as: :document
  get '/stop_alert', to: 'users#stop_alert'
  get '/resources/chat_rooms', to: 'chat_rooms#index'
  get 'resources/chat_rooms/:id', to: 'chat_rooms#show', as: :chat_room
  post 'resources/chat_rooms/:chat_room_id/chat_messages', to: 'chat_messages#create', as: :chat_room_chat_messages

  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => "/cable"

  # resources :chat_rooms, only: [:show] do
  #   resources :chat_messages, only: [:create]
  # end


  resources :alerts, only: [:index, :create, :update, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alert.rb
class Alert < ApplicationRecord

  reverse_geocoded_by :latitude, :longitude, params: { language: 'fr' }
  belongs_to :user
  has_many :messages, dependent: :destroy
  validates :started_at, presence: true

  after_create :send_message
  after_validation :reverse_geocode

  private

  def send_message
    SendMessageJob.perform_later(self.id) if self.user.contacts.any?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :content, presence: true, allow_blank: false
  after_create :broadcast_message

  def from?(some_user)
    user == some_user
  end

  def broadcast_message
    ActionCable.server.broadcast("chat_room_#{self.chat_room.id}", {
      message_partial: ApplicationController.renderer.render(
        partial: "chat_messages/message",
        locals: { chat_message: self, user_is_messages_author: false }),
      current_user_id: user.id
    })
  end
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_messages, dependent: :destroy
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :first_name, :last_name, :phone_number, presence: true
  validates :phone_number, uniqueness: true
  validates :phone_number, format: { with: /\A\+41\d{9}\z/,
    message: "n'est pas au bon format. Ex: +41 76 557 58 52" }
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :alert
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy,
                           inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :alerts, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
end

app/controllers/alerts_controller.rb
require 'nexmo'


class AlertsController < ApplicationController


  def index
    @alerts = Alert.where("started_at::date = ? AND ended_at IS NULL", Date.today)
    @markers = @alerts.map do |alert|
      {
        lat: alert.latitude,
        lng: alert.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { alert: alert }),
        image_url: helpers.asset_url('marker.png')
      }
    end
  end

  def show
    @alert = Alert.find(params[:id])
  end

  def create
    @alert = Alert.new(alert_params)
    @alert.user = current_user
    @alert.started_at = DateTime.now
    if @alert.save
      render json: {path: stop_path}
    else
      render :new
    end
  end

  def update
    @alert = Alert.find(params[:id])
    @alert.update(ended_at: DateTime.now)
    redirect_to root_path
  end

  private

  def alert_params
    params.require(:alert).permit(:latitude, :longitude)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    @chatroom = true
    @chat_rooms = ChatRoom.all
    @chat_room = ChatRoom.includes(chat_messages: :user).find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    @user = current_user
  end

  def create
    @contact = Contact.new(contact_params)
    @user = current_user
    @contact.user = @user

    @contact.phone_number = "+41#{@contact.phone_number.delete(' ')}"

    if @contact.save
      redirect_to user_path(@user)
      flash.alert = "Contact crée avec succès"
    else
      render :new
    end
  end

  def edit
    @user = current_user
    @contact = Contact.find(params[:user_id])
  end

  def update
    @contact = Contact.find(params[:id])
    @user = current_user

    if @contact.update(contact_params)
      redirect_to user_path(current_user)
      flash.alert = "Contact modifié avec succès"
    else
      render :edit
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phone_number)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.all
  end

  def show
    @document = Document.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @button_page = true
  end

  def stop
    @alert = current_user.alerts.last
    @contacts = current_user.contacts
  end

  def resources
    @chat_rooms = ChatRoom.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :stop_alert
  def show
    @user = User.find(params[:id])
    @contacts = @user.contacts
  end

  def stop_alert

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="description" content="Supernana est une application pour lutter contre le harcèlement de rue. Elle déclenche une alarme et prévient vos proches en cas d'agression. Elle met également à disposition plusieurs ressources pour s'informer et agir contre ce problème.">
    <meta charset="UTF-8">
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.2/mapbox-gl-directions.js"></script>
    <link
      rel="stylesheet"
      href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.2/mapbox-gl-directions.css"
      type="text/css"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SuperNana</title>
    <%= favicon_link_tag asset_path('favicon-32.png') %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="<%= @button_page ? 'button-page' : ''%>">
    <%= render 'shared/navbar' unless @chatroom %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="s-container">
  <div class="item-container">

    <% if user_signed_in? %>
      <%= link_to "#", id: "location", data: {path: alerts_url} do %>
        <div id="bm"></div>
      <% end %>
    <% else %>
      <%= link_to stop_alert_path, id: "location" do %>
        <div id="bm"></div>
      <% end %>
    <% end %>

    <%= link_to ("Voir les alertes du jour").html_safe, alerts_path, class: 'day-alerts' %>
    </div>
</div>

app/views/pages/resources.html.erb
<div class="s-container">

  <div class="resources-container">

  <%= link_to chat_room_path(@chat_rooms.first.id) do %>
      <div class="resources-text card-chat">
        <i class="fas fa-arrow-right"></i>
        <h3>Discuter</h3>
      </div>
  <% end %>

  <%= link_to documents_path do %>
      <div class="resources-text card-infos">
        <i class="fas fa-arrow-right"></i>
        <h3>S'informer</h3>
      </div>
  <% end %>

  <%= link_to informations_path do %>
      <div class="resources-text card-agir">
        <i class="fas fa-arrow-right"></i>
        <h3>Agir</h3>
      </div>
  <% end %>

  </div>
</div>

app/views/pages/stop.html.erb
<div class="green-box-container">
  <div class="s-container">
    <div class="item-container">
      <div>
        <%= link_to alert_path(@alert), method: :patch do %>
          <div id="bm-stop-button"></div>
        <% end %>
      </div>
    </div>

    <div class="item-container">
      <div class="alert-messages-container">

        <div class="alert-messages">
          <i class="fab fa-pagelines"></i>
          <p>Pas de panique...</p>
        </div>

      <% unless current_user.contacts.first == nil %>
        <div class="alert-messages">
          <i class="fab fa-telegram-plane"></i>
          <p>
            Nous avons envoyé un message à
            <% @contacts.each do |contact| %>
              <strong><%= contact.first_name %></strong>
            <% end %>
          </p>
        </div>
      <% end %>

        <div class="alert-messages">
          <i class="fas fa-map-marker-alt"></i>
          <div>
            <p>Votre géolocalisation:</p>
            <p><%= @alert.address %></p>
          </div>
        </div>

      </div>
    </div>

    <%= audio_tag "alarm.wav", autoplay: true %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div id="main">
  <button class="openbtn"><i class="fas fa-chevron-left"></i></button>
</div>

<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn">×</a>
  <div class="sidebar-logo">
    <%= link_to "/" do %>
      <%= image_tag "s-logo.png" %>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <%= link_to "Mon profil", user_path(current_user) %>
    <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Se connecter", new_user_session_path %>
  <% end %>
  <%= link_to "Chat & Infos", resources_path %>
</div>