config/routes.rb
Rails.application.routes.draw do
  get 'informations/index'
  devise_for :users


  resources :users, only: [:show] do
    resources :contacts, only: [:new, :create, :edit, :update]
  end
  root to: 'pages#home'

  get '/stop', to: 'pages#stop'
  get '/resources', to: 'pages#resources'
  get '/resources/documents', to: 'documents#index', as: :documents
  get '/resources/contacts', to: 'informations#index', as: :informations
  get '/resources/documents/:id', to: 'documents#show', as: :document
  get '/stop_alert', to: 'users#stop_alert'
  get '/resources/chat_rooms', to: 'chat_rooms#index'
  get 'resources/chat_rooms/:id', to: 'chat_rooms#show', as: :chat_room
  post 'resources/chat_rooms/:chat_room_id/chat_messages', to: 'chat_messages#create', as: :chat_room_chat_messages

  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => "/cable"

  # resources :chat_rooms, only: [:show] do
  #   resources :chat_messages, only: [:create]
  # end


  resources :alerts, only: [:index, :create, :update, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alert.rb
class Alert < ApplicationRecord

  reverse_geocoded_by :latitude, :longitude, params: { language: 'fr' }
  belongs_to :user
  has_many :messages, dependent: :destroy
  validates :started_at, presence: true

  after_create :send_message
  after_validation :reverse_geocode

  private

  def send_message
    SendMessageJob.perform_later(self.id) if self.user.contacts.any?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :content, presence: true, allow_blank: false
  after_create :broadcast_message

  def from?(some_user)
    user == some_user
  end

  def broadcast_message
    ActionCable.server.broadcast("chat_room_#{self.chat_room.id}", {
      message_partial: ApplicationController.renderer.render(
        partial: "chat_messages/message",
        locals: { chat_message: self, user_is_messages_author: false }),
      current_user_id: user.id
    })
  end
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_messages, dependent: :destroy
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :first_name, :last_name, :phone_number, presence: true
  validates :phone_number, uniqueness: true
  validates :phone_number, format: { with: /\A\+41\d{9}\z/,
    message: "n'est pas au bon format. Ex: +41 76 557 58 52" }
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :alert
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy,
                           inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :alerts, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
end

app/controllers/alerts_controller.rb
require 'nexmo'


class AlertsController < ApplicationController


  def index
    @alerts = Alert.where("started_at::date = ? AND ended_at IS NULL", Date.today)
    @markers = @alerts.map do |alert|
      {
        lat: alert.latitude,
        lng: alert.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { alert: alert }),
        image_url: helpers.asset_url('marker.png')
      }
    end
  end

  def show
    @alert = Alert.find(params[:id])
  end

  def create
    @alert = Alert.new(alert_params)
    @alert.user = current_user
    @alert.started_at = DateTime.now
    if @alert.save
      render json: {path: stop_path}
    else
      render :new
    end
  end

  def update
    @alert = Alert.find(params[:id])
    @alert.update(ended_at: DateTime.now)
    redirect_to root_path
  end

  private

  def alert_params
    params.require(:alert).permit(:latitude, :longitude)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
def create
    @chat_message = ChatMessage.new(message_params)
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @chat_message.chat_room = @chat_room
    @chat_message.user = current_user
    if @chat_message.save
      respond_to do |format|
        format.html { redirect_to chat_room_path(@chat_room) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render "chat_rooms/show" }
        format.js
      end
    end
  end

  private

  def message_params
    params.require(:chat_message).permit(:content)
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    @chatroom = true
    @chat_rooms = ChatRoom.all
    @chat_room = ChatRoom.includes(chat_messages: :user).find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    @user = current_user
  end

  def create
    @contact = Contact.new(contact_params)
    @user = current_user
    @contact.user = @user

    @contact.phone_number = "+41#{@contact.phone_number.delete(' ')}"

    if @contact.save
      redirect_to user_path(@user)
      flash.alert = "Contact crée avec succès"
    else
      render :new
    end
  end

  def edit
    @user = current_user
    @contact = Contact.find(params[:user_id])
  end

  def update
    @contact = Contact.find(params[:id])
    @user = current_user

    if @contact.update(contact_params)
      redirect_to user_path(current_user)
      flash.alert = "Contact modifié avec succès"
    else
      render :edit
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phone_number)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.all
  end

  def show
    @document = Document.find(params[:id])
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  def index
    @informations = Information.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @button_page = true
  end

  def stop
    @alert = current_user.alerts.last
    @contacts = current_user.contacts
  end

  def resources
    @chat_rooms = ChatRoom.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :stop_alert
  def show
    @user = User.find(params[:id])
    @contacts = @user.contacts
  end

  def stop_alert

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alerts/_info_window.html.erb
<p>


<% if (((Time.now - alert.started_at)/60).to_i) <= 60 %>
  Alerte créée il y a <%= (((Time.now - alert.started_at)/60).to_i) == 1 ? "#{((Time.now - alert.started_at)/60).to_i} minute" : "#{((Time.now - alert.started_at)/60).to_i} minutes" %>
<% else %>
  Alerte créée il y a plus d'une heure
<% end %>

par <strong><%= alert.user.first_name %> <%= alert.user.last_name %></strong>

<% if alert.ended_at? %>
  <% if (((Time.now - alert.ended_at)/60).to_i) <= 60 %>
    et arrêtée il y a <%= (((Time.now - alert.ended_at)/60).to_i) == 1 ? "#{((Time.now - alert.ended_at)/60).to_i} minute" : "#{((Time.now - alert.ended_at)/60).to_i} minutes" %>
  <% else %>
    et arrêtée il y a plus d'une heure.
  <% end %>
<% else %>
  et elle est toujours active!!!
<% end %>


</p>

app/views/alerts/create.html.erb
<h1>Alerts#create</h1>
<p>Find me in app/views/alerts/create.html.erb</p>

app/views/alerts/index.html.erb
<div class="form-container">

  <div class="green-bg">
    <div class= "s-container">
        <div class="item-container">
          <h1>Les alertes du jour</h1>
        </div>
    </div>
  </div>

  <div class="item-container">
    <% if @alerts.size == 0 %>
    <div class="ouf">
      <p>Ouf! Pas d'alerte pour le moment</p>
    </div>
    <% end %>
    <div
      id="map"
      data-markers= "<%= @markers.to_json %>"
      data-mapbox-api-key= "<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div>
</div>

app/views/alerts/show.html.erb
<dis class="s-container">

  <div class="item-container">
    <% if (((Time.now - @alert.started_at)/60).to_i) <= 60 %>
      <h4> Cette alerte a été crée il y a <%= (((Time.now - @alert.started_at)/60).to_i) == 1 ? "#{((Time.now - @alert.started_at)/60).to_i} minute" : "#{((Time.now - @alert.started_at)/60).to_i} minutes." %></h4>
    <% else %>
      <h4>Cette alerte a été crée il y a plus d'une heure. </h4>
    <% end %>


    <% if @alert.ended_at? %>
      <% if (((Time.now - @alert.ended_at)/60).to_i) <= 60 %>
        <h4>Cette alerte a été arrêtée il y a <%= (((Time.now - @alert.ended_at)/60).to_i) == 1 ? "#{((Time.now - @alert.ended_at)/60).to_i} minute" : "#{((Time.now - @alert.ended_at)/60).to_i} minutes." %></h4>
      <% else %>
        <h4>Cette alerte a été arrêtée il y a plus d'une heure. </h4>
      <% end %>
    <% else %>
      <h4>Cette alerte est toujours active!!!</h4>
    <% end %>

    <p><%= link_to "Retour", alerts_path %></p>

  </div>

</dis>

app/views/alerts/stop.html.erb
<h1>Alerts#stop</h1>
<p>Find me in app/views/alerts/stop.html.erb</p>

app/views/alerts/update.html.erb
<h1>Alerts#update</h1>
<p>Find me in app/views/alerts/update.html.erb</p>

app/views/chat_messages/_message.html.erb
<div class="message <%= user_is_messages_author ? "right" : "" %>">
  <div class="avatar-care">
    <% if chat_message.user.photo.attached? %>
      <%= cl_image_tag chat_message.user.photo.key, width: 150, height: 150, gravity: :face, crop: :thumb, :zoom=>1.1, class: 'avatar-chat' %>
    <% else %>
      <%= image_tag "profile.png", class: 'avatar' %>
    <% end %>
  </div>

  <div class="message-content">
  <div class="inline-list"><p><strong><%= chat_message.user.first_name %> <%= chat_message.user.last_name %></strong></p><p class="chat-date"><%= chat_message.created_at.strftime("%d.%m.%Y %H:%M") %></p></div>
    <p><%= chat_message.content %></p>
  </div>
</div>

app/views/chat_messages/create.js.erb
function insertMessage(chat_message) {
  const messageVide = document.querySelector('.message-vide');

  if (messageVide) {
    messageVide.parentNode.removeChild(messageVide);
  }

  const messagesContainer = document.querySelector('.messages');
  messagesContainer.insertAdjacentHTML('beforeend', chat_message);
  const input = document.querySelector('#chat_message_content');
  input.value = '';
  input.blur();
  scrollLastMessageIntoView();
}


<% if @chat_message.errors.any? %>
  ////
<% else %>
  insertMessage('<%= j render "message", chat_message: @chat_message, user_is_messages_author: true %>');
<% end %>

app/views/chat_rooms/index.html.erb
<h1>Bienvenue sur la communauté Supernana !</h1>
<p class="text-center">Rejoignez une chatroom et exprimez-vous !</p>
<div class= "s-container">
  <% @chat_rooms.each do |chat_room| %>
    <div class="doc-container">
      <h3><%= chat_room.name %></h3>

      <%= link_to chat_room_path(chat_room) do %>
        <i class="fas fa-arrow-right"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/chat_rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class= "chat-menu">
        <div class="chat-menu-title-element">
          <p>Tous les channels</p>
        </div>
          <input class="menu-btn" type="checkbox" id="menu-btn" />
          <label class="menu-icon" for="menu-btn"><span class="navicon"></span></label>
        <ul class="menu">
          <%= link_to resources_path do %>
            <p><i class="fas fa-arrow-right m-2"></i>Retour aux infos</p>
          <% end %>
          <% @chat_rooms.each do |chat_room| %>
            <%= link_to chat_room_path(chat_room) do %>
              <li><%= chat_room.name %></li>
            <% end %>
          <% end %>
        </ul>
      </div>

      <div class="chat-header"><h4>#<%= @chat_room.name %></h4></div>
      <div class="messages">

        <% if @chat_room.chat_messages.empty? %>
          <div class="message-vide">
            <h3>Oops..ce chat est vide. Soyez la première à poster un message !</h3>
          </div>
        <% else %>
          <% @chat_room.chat_messages.each do |message| %>
            <%= render "chat_messages/message", chat_message: message, user_is_messages_author:
            message.user == current_user %>
          <% end %>
        <% end %>
      </div>
      <div id="create-message">
        <%= simple_form_for [ @chat_room, ChatMessage.new ], remote: true, html: {autocomplete: "off" } do |f| %>
          <%= f.input :content, label: false, autofocus: true, placeholder: "Écrivez votre message ici..." %>
          <%= button_tag type: :submit, class: 's-button' do %>
            <i class="fas fa-paper-plane"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% content_for :after_js do %>
  <script>
    scrollLastMessageIntoView();
    App['chat_room_<%= @chat_room.id %>'] = App.cable.subscriptions.create({ channel: 'ChatRoomsChannel', chat_room_id: <%= @chat_room.id %> }, {
      received: (data) => {
        if (data.current_user_id !== <%= current_user.id %>) {
          const messagesContainer = document.querySelector('.messages');
          messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
          scrollLastMessageIntoView();
        }
      }
    })
  </script>
<% end %>

app/views/contacts/edit.erb
<div class="form-container">  <div class="green-bg">    <div class= "s-container">        <div class="item-container">          <h1>Editez le contact d'urgence</h1>        </div>    </div>  </div>  <div class="item-container">    <%= simple_form_for [@user, @contact], :method => :patch do |f| %>    <%= f.input :first_name, as: :string, label: 'Prénom', autofocus: true, class: 's-input' %>    <%= f.input :last_name, as: :string, label: 'Nom', autofocus: true %>    <%= f.input :phone_number, as: :string, label: 'Téléphone', autofocus: true %>    <%= f.button :submit, 'Editer le contact', class: 's-button' %>    <% end %>  </div></div>

app/views/contacts/new.html.erb
<div class="form-container">

  <div class="green-bg">
    <div class= "s-container">
        <div class="item-container">
          <h1>Ajoutez un contact d'urgence</h1>
        </div>
    </div>
  </div>

  <div class="item-container">
    <%= simple_form_for [@user, @contact] do |f| %>
    <%= f.input :first_name, as: :string, placeholder: 'Paul', label: 'Prénom', autofocus: true, class: 's-input' %>
    <%= f.input :last_name, as: :string, placeholder: 'Lepoulp', label: 'Nom', autofocus: true %>
    <div class="phone-number">
      <%= f.input :phone_number, as: :string, placeholder: '76 557 53 52', label: 'Téléphone', autofocus: true %>
    </div>
    <%= f.button :submit, 'Ajouter le contact', class: 's-button' %>
    <% end %>
  </div>

</div>

app/views/documents/index.html.erb
<div class="fix-background illustration-docs"></div>

<div class="white-background">
  <div class= "s-container">
    <h1 class="info-title">S'informer</h1>
      <% @documents.each do |document| %>
        <div class="doc-container">
          <h3><%= document.title %></h3>
          <p> Un article de <%= document.author %></p>

          <%= link_to document_path(document) do %>
            <i class="fas fa-arrow-right"></i>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/documents/show.html.erb
 <div class="green-bg">
    <div class= "s-container">
        <div class="item-container">
          <h1><%= @document.title %></h1>
        </div>
    </div>
  </div>

<div class= "s-container">
  <div class="item-container">
    <p><%= @document.content %></p>
    <div class="button-container">
      <%= link_to 'Retour à la doc', documents_path, class: "s-button" %>
      <%= link_to 'Consulter cette article en ligne', @document.url, :target => "_blank", class: "s-button" %>
    </div>
  </div>
</div>

app/views/informations/index.html.erb
<div class="fix-background illustration-infos"></div>

<div class="white-background">
  <div class="s-container">
    <h1 class="info-title">Agir</h1>

      <% @informations.each do |information| %>
      <div class="contact-infos-container">
          <h3><%= information.title %></h3>
          <p><%= information.description %></p>
          <div class="contacts-links">
            <div class="contacts-links-infos">
              <i class="fas fa-phone"></i>
              <a href="tel:<%= information.phone_number %>"><%= information.phone_number %></a>
            </div>

            <div class="contacts-links-infos">
              <i class="fas fa-envelope-open-text"></i>
              <a href="mailto:<%= information.email %>"><%= information.email %></a>
            </div>

            <div class="contacts-links-infos">
              <i class="fas fa-link"></i>
              <a href="<%= information.website %>"><%= information.website %></a>
            </div>

            <div class="contacts-links-infos">
              <i class="fas fa-map-marker-alt"></i>
              <p><%= information.location %></p>
            </div>

          </div>
      </div>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="green-bg">
  <div class="item-container">
      <%= link_to edit_user_registration_path do %>
        <i class="fas fa-cog settings"></i>
      <% end %>
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, width: 150, height: 150, gravity: :face, crop: :thumb, :zoom=>1.1, class: 'avatar-large' %>
      <% else %>
        <%= image_tag "profile.png", class: 'avatar-large' %>
      <% end %>
    <div class="profil-infos">
      <p><%= @user.first_name.capitalize %></p>
      <p><%= @user.last_name.capitalize %></p>
      <p><%= @user.email %></p>
    </div>
  </div>
</div>

<div class="item-container">
  <div class="info-container">
    <h4>Contacts d'urgence</h4>
    <% if @user.contacts.any? %>
        <% @contacts.each do |contact| %>
            <div class="profile-list">
              <p><strong><%= contact.first_name.capitalize %> <%= contact.last_name.capitalize %></strong>
              <%= contact.phone_number %></p>
              <%= link_to edit_user_contact_path(current_user.contacts.first) do %>
                <i class="fas fa-cog"></i>
              <% end %>
            </div>
        <% end %>
    <% else %>
      <p>Pas de contact ajouté!</p>
    <% end %>
  </div>
  <%= link_to "Ajouter un contact", new_user_contact_path(@user), class: 's-button' %>
</div>

app/views/users/stop_alert.html.erb
<div class="green-box-container">
  <div class="s-container">

    <div class="item-container">
      <div>
        <%= link_to new_user_registration_path do %>
          <div id="bm-stop-button"></div>
        <% end %>
      </div>
    </div>

    <div class="item-container">
      <div class="alert-messages-container">
        <div class="alert-messages">
          <i class="fab fa-pagelines"></i>
          <p>Pas de panique...</p>
        </div>

        <div class="alert-messages">
          <i class="fas fa-meteor"></i>
          <div>
            <p>Pensez-y, avec un compte utilisateur nous pouvons aussi: </p>
            <ul>
              <li>envoyer un message à un contact d'urgence prédéfini</li>
              <li>vous géolocaliser auprès de tous les utilisateurs de notre app!</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <%= audio_tag "alarm.wav", autoplay: true %>
  </div>
</div>